### PR TITLE
Unify 2.12 and 2.13 branches

### PR DESCRIPTION
**Pull request by rossabaker**
This supports Scala 2.12 and 2.13 from the same branch. The few divergences are buried in the new package-private `XCompat` object.

### CODE REVIEW

**Comment by J-mie6** [comment]
This looks great! Didn't realise you could do this, when it's packaged I assume you get two jars? I'll check to make sure it's working fine with projects I depend on it for and merge after. Thanks!

**Comment by rossabaker** [comment]
Yes, but I just noticed they're called `root` now.  I will fix that.

**Comment by rossabaker** [comment]
Scratch that `root` comment.  I was on a different branch.  

From this PR, `+publishLocal` puts the jars in your Ivy cache:

```
...
[info] 	published parsley_2.12 to /home/ross/.ivy2/local/parsley/parsley_2.12/1.5.0/jars/parsley_2.12.jar
...
[info] 	published parsley_2.13 to /home/ross/.ivy2/local/parsley/parsley_2.13/1.5.0/jars/parsley_2.13.jar
...
```

Note that the Scala version only appears to down the minor version, not the patch.  This matches Scala's binary guarantees and integrates nicely with sbt:

```scala
    libraryDependencies ++= Seq(
      "parsley" %% "parsley" % "1.5.0"
    ),
```

The next step is to publish those jars to Maven Central, so `publishLocal` on each machine isn't necessary.  I'll have a PR for that in a bit.

It's also of course still possible to copy those jars and check them directly into source control, but you lose a lot of sbt's tooling in doing so.

**Comment by J-mie6** [comment]
Ok great, thanks! Usually I use git cloning with sbt to depend on Parsley. I had meant to host it on maven, but it seemed like quite an involved process to get it up there to begin with. I should probably take a second look.

**Comment by J-mie6** [comment]
So I did end up having a problem when using this branch:

In a separate (Dotty 0.27) project, I had a dependency of the form:

```
lazy val parsley = RootProject(uri("git://github.com/J-mie6/Parsley.git#2.13"))
```

This worked fine before, however with the new build.sbt attempting to compile with this gives:

```
sbt.librarymanagement.ResolveException: Error downloading parsley:parsley_0.27:1.5.0
[error]   Not found
[error]   Not found
[error]   not found: /home/jamie/.ivy2/local/parsley/parsley_0.27/1.5.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/parsley/parsley_0.27/1.5.0/parsley_0.27-1.5.0.pom
````

It's not particularly important that this is resolved (because I made a backup of the old branch and when I publish via maven it'll I'll be able to grab it that way), but given we are both using this with dotty it seems like it might be important?

**Comment by rossabaker** [comment]
Add this to `project/plugins.sbt`, if not already there:

```sbt
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.4")
```

Then you should be able to use Dotty's Scala compatibility mode:

```sbt
    libraryDependencies ++= Seq(
      ("parsley" %% "parsley" % "1.5.0").withDottyCompat(scalaVersion.value)
    ),
```

Better yet, we can cross-build on Dotty like we do for the two Scala versions.  I'll see if I can throw together a PR for that.

**Pull request merged**
